/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcula.h"

// Função de adição realizada pelo Servidor

int * add_100_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Requisicao de adicao para %d e %d\n", argp->x, argp->y);
	result = argp->x + argp->y;
	return (&result);
}

// Função de subtração realizada pelo Servidor

int * sub_100_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Requisicao de subtracao para %d e %d\n", argp->x, argp->y);
	result = argp->x - argp->y;
	return (&result);
}

// Função de multiplicação realizada pelo Servidor

int * mul_100_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Requisicao de multiplicacao para %d e %d\n\n", argp->x, argp->y);
	result = argp->x * argp->y;

	return &result;
}

// Função de divisão realizada pelo Servidor

double * divi_100_svc(operandos *argp, struct svc_req *rqstp)
{
	static double  result;

	printf("Requisicao de divisao para %d e %d\n\n", argp->x, argp->y);
	result = (double)argp->x / (double)argp->y;

	return &result;
}
