/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcula.h"
#include <stdio.h>

// Função de add realiza o pedido para o servidor realizar a adicao

int add( CLIENT *clnt, int x, int y) {
	operandos ops;
	int *result;

	ops.x = x;
	ops.y = y;

	result = add_100(&ops,clnt);
	if (result == NULL) {
		fprintf(stderr, "Problema na chamada RPC\n");
		exit(0);
	}
	return(*result);
}

// Função de sub realiza o pedido para o servidor realizar a subtração

int sub( CLIENT *clnt, int x, int y) {
	operandos ops;
	int *result;

	ops.x = x;
	ops.y = y;

	result = sub_100(&ops,clnt);
	if (result==NULL) {
		fprintf(stderr,"Problema na chamda RPC\n");
		exit(0);
	}
	return(*result);
}

// Função de mul realiza o pedido para o servidor realizar a multiplicação

int mul( CLIENT *clnt, int x, int y) {
	operandos ops;
	int *result;

	ops.x = x;
	ops.y = y;

	result = mul_100(&ops,clnt);
	if (result==NULL) {
		fprintf(stderr,"Problema na chamda RPC\n");
		exit(0);
	}
	return(*result);
}

// Função de divi realiza o pedido para o servidor realizar a divisao

double divi( CLIENT *clnt, int x, int y) {
	operandos ops;
	double *result;

	ops.x = x;
	ops.y = y;

	result = divi_100(&ops,clnt);
	if (result==NULL) {
		fprintf(stderr,"Problema na chamda RPC\n");
		exit(0);
	}
	return(*result);
}

int main (int argc, char *argv[])
{

	printf("Recebe 3 argumentos os dois primeiros são numeros e o terceiro é a operação 1 para adicao, 2 para subtracao, 3 para multiplicao, 4 para divisão. \n");

	CLIENT *clnt;
	int x;
	int y;
	int z;
	

	if (argc!=5) {
		fprintf(stderr, "Uso: %s hostname num1 num2\n", argv[0]);
		exit(0);
	}

	clnt = clnt_create(argv[1], PROG, VERSAO, "udp");

	if (clnt == (CLIENT *) NULL) {
		clnt_pcreateerror(argv[1]);
		exit(1);
	}

	x = atoi(argv[2]);
	y = atoi(argv[3]);
	z = atoi(argv[4]);

	//Dependendo da entrada do usuário para o terceiro argumento ele executa determinada operação.
	// 1 - para adição
	// 2 - para subtração
	// 3 - para multiplicação
	// 4 - para divisão

	switch(z){
		case 1:
			printf("%d + %d = %d\n",x,y, add(clnt,x,y));
			break;
		case 2:
			printf("%d - %d = %d\n",x,y, sub(clnt,x,y));
			break;
		case 3:
			printf("%d * %d = %d\n",x,y, mul(clnt,x,y));
			break;
		case 4:
			printf("%d / %d = %lf\n",x,y, divi(clnt,x,y));
			break;
	}

	return(0);
}